### ISSUE TITLE
Error: spawn php ENOENT when opening .php file

### ISSUE THREAD

**Issue by KK2345** [AtomLinter/linter-csslint#130]
When I try to edit php file I get following error:
```
Error: spawn php ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

**Comment by Arcanemagus** [comment]
I'm not sure why you filed this here... I'm guessing you have `linter-php` installed? You need to tell it where `php` is located on your system in the settings.
