### ISSUE TITLE
HALP

### ISSUE THREAD

**Issue by moriahcgibbs** [AtomLinter/linter-csslint#173]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.12.6
**Thrown From**: [linter-csslint](https://github.com/AtomLinter/linter-csslint) package, v2.0.0

### Stack Trace

Failed to activate the linter-csslint package

```
At window.requestIdleCallback is not a function

TypeError: window.requestIdleCallback is not a function
    at Object.activate (/Users/moriahgibbs/.atom/packages/linter-csslint/lib/main.js:42:29)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "predawn-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.8.7
emmet, v2.4.3
linter, v1.11.18
linter-csslint, v2.0.0
linter-php, v1.3.2
linter-tidy, v2.3.1
predawn-ui, v1.0.7

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
Your Atom version is positively ancient, upgrade to the current stable version 😉.
