### ISSUE TITLE
Error running CSSLint Error: 'node' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by zitengine** [AtomLinter/linter-csslint#184]
[Linter] Error running CSSLint Error: 'node' is not recognized as an internal or external command,
operable program or batch file.
    at ChildProcess.<anonymous> (C:\Users\Abhay\.atom\packages\linter-csslint\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by Arcanemagus** [comment]
You need to have Node.js installed on your system to run `csslint`. It's one of their many mistakes that that is hard coded in there.

**Comment by hassanabdelmenem** [comment]
> You need to have Node.js installed on your system to run `csslint`. It's one of their many mistakes that that is hard coded in there.

how to install Node.js on windows 10 machine

**Comment by Arcanemagus** [comment]
> how to install Node.js on windows 10 machine

http://lmgtfy.com/?q=how+to+install+Node.js+on+windows+10+machine
