### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by 973782523** [AtomLinter/linter-csslint#185]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0-beta1 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [linter-csslint](https://github.com/AtomLinter/linter-csslint) package 2.0.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At module.js:472

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.24.0-beta1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.24.0-beta1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.24.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at installLinterCsslintDeps (/packages/linter-csslint/lib/main.js:33:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-modules 1.8.0 
atom-ternjs 0.18.3 
atom-ternjs 0.18.3 
autoclose-html 0.24.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.8 
file-types 0.5.5 
language-javascript-jsx 0.3.7 
linter-csslint 2.0.0 
minimap 4.28.2 
node_modules undefined 
simplified-chinese-menu 5.3.4 
ZenScript 0.2.5 
```

**Comment by Arcanemagus** [comment]
Please re-install the package, Atom sometimes fails to install dependencies.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
