### ISSUE TITLE
Error Message everytime saved css file

### ISSUE THREAD

**Issue by draindra9** [AtomLinter/linter-csslint#208]
Hey,  i'm using Atom 1.33 and linter-csslint 2.0.1

It's all started when this message appear every time i try to save .css document
[Linter] Error running CSSLint
See Console for more info. (Open View -> Developer -> Toggle Developer Tools)

when i open Atom's developer tool, it shows an error message like this,

C:\Users\Sukmaindra\.atom\packages\linter\lib\linter-registry.js:159 [Linter] Error running CSSLint TypeError: Cannot read property 'length' of null
  at Object.<anonymous> (file:///C:/Users/Sukmaindra/.atom/packages/linter-csslint/lib/main.js:142:20)
    at Generator.next (<anonymous>)
    at step (C:\Users\Sukmaindra\.atom\packages\linter-csslint\lib\main.js:5:273)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

is there any fix?

**Comment by Arcanemagus** [comment]
Looks like this provider isn't handling the case where execution has been cancelled by a newer run properly.

**Comment by Akumidina** [comment]
I have the same issue

**Comment by Ankursehrawat15** [comment]
same issue
