### ISSUE TITLE
Error while running CSSLint! Fresh install

### ISSUE THREAD

**Issue by lydenyardley** [AtomLinter/linter-csslint#232]
Freshly installed Atom > installed CSSLint > it prompted the install of a few dependencies > doesn't work, and produces this error:

```
main.js? [sm]:110 Error: path.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Unexpected token ILLEGAL
    at runInThisContext (node.js:741:18)
    at NativeModule.compile (node.js:804:14)
    at Function.NativeModule.require (node.js:774:18)
    at startup (node.js:93:31)
    at node.js:814:3
    at runInThisContext (node.js:741:18)
    at NativeModule.compile (node.js:804:14)
    at Function.NativeModule.require (node.js:774:18)
    at startup (node.js:93:31)
    at node.js:814:3
    at ChildProcess.<anonymous> (/Users/lydenyardley/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by Arcanemagus** [comment]
Does `csslint` itself work from the terminal? What version of Atom are you using?

**Comment by lydenyardley** [comment]
Unfortunately, I have no idea about the terminal - I just installed the package from within Atom. Mac version 1.35.0

**Comment by Arcanemagus** [comment]
Since this is a wrapper around running `csslint`, you need to get that working _first_ before you can use it here.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
