### ISSUE TITLE
Failed to load the linter-csslint package

### ISSUE THREAD

**Issue by mastr358** [AtomLinter/linter-csslint#45]
1. Error appeared after running Atom. There were no updates prior to this error, and yesterday, it worked fine.
2. Will provide list of packages on request.

**Atom Version**: 1.0.15
**System**: Win 7 Pro SP1
**Thrown From**: [linter-csslint](https://github.com/AtomLinter/linter-csslint) package, v1.0.5

### Stack Trace

Failed to load the linter-csslint package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\user\.atom\packages\linter-csslint\lib\main.coffee:1:11)
    at Object.<anonymous> (C:\Users\user\.atom\packages\linter-csslint\lib\main.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\user\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Remote-FTP"
    ]
  },
  "linter-csslint": {}
}
```

### Installed Packages

```coffee
# User
jshint, v1.8.0
linter, v1.6.0
linter-csslint, v1.0.5
minimap, v4.13.3

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
```
cd ~/.atom/packages/linter-csslint
apm install
```

**Comment by pablobb** [comment]
As above, same error for jshint and csslint.

Steps abve with navigating to pluginfolder and running apm install did not work.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1
**Thrown From**: [linter-csslint](https://github.com/AtomLinter/linter-csslint) package, v1.0.7


### Stack Trace

Failed to load the linter-csslint package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Paweł\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Paweł\.atom\packages\linter-csslint\lib\main.coffee:1:11)
    at Object.<anonymous> (C:\Users\Paweł\.atom\packages\linter-csslint\lib\main.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Paweł\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "ruby-block",
      "ruby-block-converter",
      "script",
      "jslint"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.6.2
autoclose-html, v0.19.0
jquery-snippets, v11.0.0
linter-csslint, v1.0.7
linter-jshint, v1.2.1
remote-edit, v1.8.21
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
@mastr358 @pablobb From tracking down similar issues it very much looks like this is the root issue (for Atom):
https://github.com/atom/atom/issues/8891

Please follow any further news there as to when this will be fixed in Atom.

**Comment by Arcanemagus** [comment]
@mastr358 @pablobb 

[Atom v1.2.0-beta0](https://github.com/atom/atom/releases/tag/v1.2.0-beta0) has been released as a beta, and it includes the updated Electron version that reportedly fixes this issue. If you don't want to wait until v1.2.0 is officially released you can install this preview now.
