### ISSUE TITLE
Error installing v1.1.0 on Windows 10

### ISSUE THREAD

**Issue by Jhony0311** [AtomLinter/linter-csslint#61]
I'm having an error trying to install v1.1.0 on windows 10, it seems to be a Node JS issue because I tried to do manually with npm install and then apm link and it does not work too.
This is my current set up: 

apm  1.4.0
npm  2.13.3
node 0.10.40
python
git 2.6.3.windows.1
visual studio

**Comment by Arcanemagus** [comment]
Are you getting any error messages? I run and develop this on Windows 10...

**Comment by Jhony0311** [comment]
Yes, I'm getting this error:
```
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/AtomLinter/csslint.git resetting remote C:\Users\Jonathan\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\Jonathan\.atom\.apm\_git-remotes\_templates --mirror https://github.com/AtomLinter/csslint.git C:\Users\Jonathan\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1: Cloning into bare repository 'C:\Users\Jonathan\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1'...
npm ERR! git clone --template=C:\Users\Jonathan\.atom\.apm\_git-remotes\_templates --mirror https://github.com/AtomLinter/csslint.git C:\Users\Jonathan\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1: fatal: unable to access 'https://github.com/AtomLinter/csslint.git/': error setting certificate verify locations:
npm ERR! git clone --template=C:\Users\Jonathan\.atom\.apm\_git-remotes\_templates --mirror https://github.com/AtomLinter/csslint.git C:\Users\Jonathan\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1:   CAfile: C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
npm ERR! git clone --template=C:\Users\Jonathan\.atom\.apm\_git-remotes\_templates --mirror https://github.com/AtomLinter/csslint.git C:\Users\Jonathan\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1:   CApath: none
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Jonathan\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Jonathan\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Jonathan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Jonathan\\.atom\\.apmrc" "install" "C:\\Users\\Jonathan\\AppData\\Local\\Temp\\d-1151030-3828-1t7mqnh\\package.tgz" "--target=0.34.0" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Jonathan\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1'...
npm ERR! fatal: unable to access 'https://github.com/AtomLinter/csslint.git/': error setting certificate verify locations:
npm ERR!   CAfile: C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
npm ERR!   CApath: none
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by Arcanemagus** [comment]
Looks like your `git` command has too old of a certificate chain to verify the GitHub certificate, is there possibly an update to however you have that installed?

**Comment by Jhony0311** [comment]
Right now I'm using v2.6.3 which is supposed to be the latest

**Comment by Arcanemagus** [comment]
Your `git` version may be up to date, but the certificates it is using for SSL aren't able to verify that GitHub's cert is valid, which is why this is failing.

I'm almost thinking of just pulling the `csslint` files into this repository until somebody starts working on it again (if ever...).

**Comment by Jhony0311** [comment]
@Arcanemagus there is a way to upgrade that certificates?

**Comment by Arcanemagus** [comment]
[This](http://stackoverflow.com/a/33336623) _might_ be what you are looking for, personally I just use the GitHub desktop app's `git` myself and haven't had issues.

**Comment by Jhony0311** [comment]
Yup, that worked perfect. The issue is solved with this. Thanks  @Arcanemagus

**Comment by Arcanemagus** [comment]
Thanks for reporting back :wink:.
