### ISSUE TITLE
Failed to activate the linter-csslint package

### ISSUE THREAD

**Issue by welcoMattic** [AtomLinter/linter-csslint#77]
Just install package and restart Atom

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-csslint](https://github.com/AtomLinter/linter-csslint) package, v1.2.0

### Stack Trace

Failed to activate the linter-csslint package

```
At Cannot find module 'atom-package-path'

Error: Cannot find module 'atom-package-path'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.install (/Users/welcomattic/.atom/packages/linter-csslint/node_modules/atom-package-deps/lib/main.js:27:12)
    at Object.module.exports.activate (/Users/welcomattic/.atom/packages/linter-csslint/lib/main.coffee:6:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.3.2
atom-material-ui, v0.8.1
autoclose-html, v0.20.0
emmet, v2.4.1
linter, v1.11.3
linter-csslint, v1.2.0
linter-htmlhint, v1.0.2
linter-jshint, v1.3.0
markdown-scroll-sync, v2.1.1
pigments, v0.23.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
This was due to a bug in a dependency that has since been fixed, you can either uninstall/reinstall this package, or run `apm rebuild` in the package's folder from a terminal to fix this. Sorry about that!

**Comment by welcoMattic** [comment]
@Arcanemagus Thanks !
